import { useEffect, useMemo, useState } from 'react';
import { useGameStore } from '../store/gameStore';
import type { ChaosLevel, Difficulty, RealityType, StrategyPreset } from '../types/game';

export function App() {
  const { save, load, startCareer, runRace, advanceRound, startDevelopment, marketAction, endSeason } = useGameStore();
  const [page, setPage] = useState<'home'|'career'|'dashboard'|'db'|'settings'>('home');
  const [year,setYear]=useState(2026); const [team,setTeam]=useState('aurora'); const [reality,setReality]=useState<RealityType>('historical'); const [chaos,setChaos]=useState<ChaosLevel>('medium'); const [difficulty,setDifficulty]=useState<Difficulty>('normal'); const [strategy,setStrategy]=useState<StrategyPreset>('balanced');
  useEffect(()=>load(),[load]);
  const selectedTeam = useMemo(()=>save?.teams.find((t)=>t.id===save.selectedTeamId),[save]);

  if(page==='home') return <div className='container'><h1>F1 Legacy Manager</h1><div className='grid grid-2'><button className='btn' onClick={()=>setPage('career')}>Novo jogo</button><button className='btn btn2' onClick={()=>save&&setPage('dashboard')}>Continuar jogo</button><button className='btn btn2' onClick={()=>setPage('db')}>Banco de dados</button><button className='btn btn2' onClick={()=>setPage('settings')}>Configurações</button></div></div>;
  if(page==='career') return <div className='container card'><h2>Criação de carreira</h2><div className='grid grid-2'><label>Ano inicial<input type='number' min={2006} max={2026} value={year} onChange={(e)=>setYear(Number(e.target.value))}/></label><label>Equipe<select value={team} onChange={(e)=>setTeam(e.target.value)}>{['aurora','titan','nova','falcon','atlas','zephyr','cobalt','vertex','solar','rookie'].map((x)=><option key={x} value={x}>{x}</option>)}</select></label><label>Realidade<select value={reality} onChange={(e)=>setReality(e.target.value as RealityType)}><option value='historical'>Histórica</option><option value='semi-realistic'>Semi-realista</option><option value='free'>Livre</option></select></label><label>Caos<select value={chaos} onChange={(e)=>setChaos(e.target.value as ChaosLevel)}><option value='low'>Baixo</option><option value='medium'>Médio</option><option value='high'>Alto</option></select></label><label>Dificuldade<select value={difficulty} onChange={(e)=>setDifficulty(e.target.value as Difficulty)}><option value='easy'>Fácil</option><option value='normal'>Normal</option><option value='hard'>Difícil</option><option value='realistic'>Realista</option></select></label></div><button className='btn' onClick={()=>{startCareer(year,team,reality,chaos,difficulty);setPage('dashboard');}}>Iniciar carreira</button></div>;
  if(!save || !selectedTeam) return <div className='container'>Sem save. <button className='btn' onClick={()=>setPage('home')}>Voltar</button></div>;

  return <div className='container'>
    <h2>{save.year} • Rodada {save.currentRound+1}/{save.tracks.length}</h2>
    <div className='tabs'><button className='btn btn2' onClick={()=>setPage('home')}>Menu</button><button className='btn' onClick={()=>runRace(strategy)}>Simular corrida</button><button className='btn btn2' onClick={()=>advanceRound()}>Avançar calendário</button><button className='btn btn2' onClick={()=>startDevelopment(save.selectedTeamId,'Asa dianteira')}>Desenvolver carro</button><button className='btn btn2' onClick={()=>marketAction('renew',selectedTeam.driverIds[0],selectedTeam.id)}>Renovar piloto #1</button><button className='btn btn2' onClick={()=>endSeason()}>Encerrar temporada</button></div>
    <label>Estratégia pré-corrida<select value={strategy} onChange={(e)=>setStrategy(e.target.value as StrategyPreset)}><option value='aggressive'>Agressiva</option><option value='balanced'>Equilibrada</option><option value='conservative'>Conservadora</option></select></label>
    <div className='grid grid-2'>
      <section className='card'><h3>Equipe</h3><p>{selectedTeam.name} ({selectedTeam.nationality})</p><p>Orçamento: ${selectedTeam.budget}M</p><p>Reputação: {selectedTeam.reputation} | Moral: {selectedTeam.morale}</p><p>Motor: {selectedTeam.motor}</p><p>Pontos: {save.teamStandings.find(s=>s.id===selectedTeam.id)?.points ?? 0}</p></section>
      <section className='card'><h3>Carro</h3><p>Aero {selectedTeam.car.aerodynamics} • Chassi {selectedTeam.car.chassis} • Motor {selectedTeam.car.engine}</p><p>Suspensão {selectedTeam.car.suspension} • Refrigeração {selectedTeam.car.cooling}</p><p>Confiabilidade {selectedTeam.car.reliability} • Peso {selectedTeam.car.weight}</p></section>
      <section className='card'><h3>Pilotos</h3><table><thead><tr><th>Nome</th><th>Overall</th><th>Status</th><th>Contrato</th></tr></thead><tbody>{save.drivers.filter((d)=>d.teamId===selectedTeam.id).map((d)=><tr key={d.id}><td>{d.name}</td><td>{d.overall}</td><td>{d.status}</td><td>{d.contractUntil}</td></tr>)}</tbody></table></section>
      <section className='card'><h3>Calendário</h3>{save.tracks.map((t,i)=><p key={t.id} style={{opacity:i===save.currentRound?1:0.6}}>{i+1}. {t.name} ({t.country}) • {t.laps} voltas</p>)}</section>
      <section className='card'><h3>Classificação pilotos</h3><table><thead><tr><th>#</th><th>Piloto</th><th>Pts</th></tr></thead><tbody>{save.driverStandings.slice(0,10).map((d,i)=><tr key={d.id}><td>{i+1}</td><td>{d.name}</td><td>{d.points}</td></tr>)}</tbody></table></section>
      <section className='card'><h3>Classificação equipes</h3><table><thead><tr><th>#</th><th>Equipe</th><th>Pts</th></tr></thead><tbody>{save.teamStandings.map((t,i)=><tr key={t.id}><td>{i+1}</td><td>{t.name}</td><td>{t.points}</td></tr>)}</tbody></table></section>
      <section className='card'><h3>Corrida (texto/tabela)</h3>{save.lastRace? <><table><thead><tr><th>Pos</th><th>Piloto</th><th>Equipe</th><th>Pneus</th><th>Gap</th><th>Status</th></tr></thead><tbody>{save.lastRace.results.map((r)=><tr key={r.driverId}><td>{r.position}</td><td>{save.drivers.find(d=>d.id===r.driverId)?.name}</td><td>{save.teams.find(t=>t.id===r.teamId)?.name}</td><td>{r.tire}</td><td>{r.gap}</td><td>{r.status}</td></tr>)}</tbody></table><h4>Eventos</h4>{save.lastRace.events.map((e,i)=><p key={i}>V{e.lap}: {e.message}</p>)}</> : <p>Sem corrida simulada.</p>}</section>
      <section className='card'><h3>Mercado e desenvolvimento</h3><p>Projetos: {save.developments.length}</p>{save.developments.slice(-5).map((p)=><p key={p.id}>{p.part}: {p.status} (ganho {p.estimatedGain})</p>)}<p>Comandos de corrida MVP: Atacar, Normal, Poupar pneus, Poupar motor, Defender, Undercut, Estender stint (representados pela estratégia global no simulador atual).</p></section>
    </div>
  </div>;
}
